### ISSUE TITLE
Wrap the network handling into Ipfs

### ISSUE THREAD

**Issue by Konubinix** [MichaelMure/Arbore-qt#17]
Each Ipfs command binds on a QNetworkReply::finished SIGNAL to get its results.

Each command then has to deal with the possible network failures.

It would be better if Ipfs would make sur the connection goes well (possibly re issuing the request) and would guaranty the command to get its result.

**Comment by MichaelMure** [comment]
Wrapping is done, need more error handling

**Comment by MichaelMure** [comment]
let's close this one and wait to see if problems actually appear with the current code.
