### ISSUE TITLE
Fix the tracking of progress in size

### ISSUE THREAD

**Issue by MichaelMure** [MichaelMure/Arbore-qt#8]
https://github.com/MichaelMure/Arbore-qt/blob/master/src/file.cpp#L33

The real size of the block is missing, we need to get that from IPFS

**Comment by Konubinix** [comment]
For the time being, we get the information via the refs command. It returns only the list of refs.
$ curl http://127.0.0.1:5001/api/v0/refs?arg=Qmc2dngaxj9AGLWBRo4LntD3NssygqgdKsd7EcSXxKaPwR&r=true&u=true
{
  "Ref": "QmVS1ETWNpBzSf8nF8Etkj6717jjc7JGpd6MXHX8RzK1Cb\n",
  "Err": ""
}{
  "Ref": "QmUzbLQJipkwM7Q75L8mNtyZT9D5N5kjxfHt35g7dyoz35\n",
  "Err": ""
}{
  "Ref": "QmRkoQDQ6AEzkpFEuCKmZB5pKshdS6irW8igNq3GKcYpC6\n",
  "Err": ""
}{
  "Ref": "QmeRWYoisSPmFCcvqUCud9MJDSSPxrsuPMiaH6qsJ6HqRq\n",
  "Err": ""
}

We could use insted the ls command that returns also the block size
$ curl 'http://127.0.0.1:5001/api/v0/ls?arg=Qmc2dngaxj9AGLWBRo4LntD3NssygqgdKsd7EcSXxKaPwR'
{
  "Objects": [
    {
      "Hash": "Qmc2dngaxj9AGLWBRo4LntD3NssygqgdKsd7EcSXxKaPwR",
      "Links": [
        {
          "Name": "",
          "Hash": "QmVS1ETWNpBzSf8nF8Etkj6717jjc7JGpd6MXHX8RzK1Cb",
          "Size": 262158,
          "Type": 2
        },
        {
          "Name": "",
          "Hash": "QmUzbLQJipkwM7Q75L8mNtyZT9D5N5kjxfHt35g7dyoz35",
          "Size": 262158,
          "Type": 2
        },
        {
          "Name": "",
          "Hash": "QmRkoQDQ6AEzkpFEuCKmZB5pKshdS6irW8igNq3GKcYpC6",
          "Size": 262158,
          "Type": 2
        },
        {
          "Name": "",
          "Hash": "QmeRWYoisSPmFCcvqUCud9MJDSSPxrsuPMiaH6qsJ6HqRq",
          "Size": 182053,
          "Type": 2
        }
      ]
    }
  ]

As far as I can tell, there is no reason why the blocks composing a file could be split in a tree. Thus we only need to go through the list resulting from ls. Am I right ?

**Comment by MichaelMure** [comment]
Just make sure than you can get the data you need even if the file is too big and its child blocks are organized in a subtree (it seems to happen with > ~ 150mo file). `graphmd` won't show you this subtree, but the webui will.

Also make sure that you can deal with blocs used multiple time inside the same file like this:
![zero](https://cloud.githubusercontent.com/assets/294669/9285569/6e0a73ee-42e7-11e5-975a-2e03b009c156.png)

This is the graph of a 10Mo file of zero.

**Comment by Konubinix** [comment]
In order to test those two particular cases
$ dd if=/dev/zero of=test bs=1M count=200
200+0 enregistrements lus
200+0 enregistrements écrits
209715200 octets (210 MB) copiés, 6,19077 s, 33,9 MB/s
$ ipfs add test
added QmXo4G557RDJQfVjg9fKW5RJkUyPJ3YS6WGEw934ZcQeVT test
$ ipfs ls QmXo4G557RDJQfVjg9fKW5RJkUyPJ3YS6WGEw934ZcQeVT
QmY4HSz1oVGdUzb8poVYPLsoqBZjH6LZrtgnme9wWn2Qko 45623854 
QmY4HSz1oVGdUzb8poVYPLsoqBZjH6LZrtgnme9wWn2Qko 45623854 
QmY4HSz1oVGdUzb8poVYPLsoqBZjH6LZrtgnme9wWn2Qko 45623854 
QmY4HSz1oVGdUzb8poVYPLsoqBZjH6LZrtgnme9wWn2Qko 45623854 
QmWVxvresoeadRbCeG4BmvsoSsqHV7VwUNuGK6nUCKKFGQ 27269434
$ ipfs refs -r QmXo4G557RDJQfVjg9fKW5RJkUyPJ3YS6WGEw934ZcQeVT|wc -l
805
$ graphmd QmXo4G557RDJQfVjg9fKW5RJkUyPJ3YS6WGEw934ZcQeVT|dot -Tx11

**Comment by Konubinix** [comment]
ipfs ls does not have a recursive version.
We have to choose between:
1. implement the recursive ipfs ls in ipfs
2. recursively walk into the ls results
3. run ipfs refs -r and call ipfs ls for each of them

The option 3 looses the subtree information since it prints a flat list of blocks

**Comment by MichaelMure** [comment]
option 1 would break the semantics in ipfs, so not an option
option 3 would lead to a lot of http query

The best way IMHO would be to have `ipfs ref` also output the size of each blocks, but I actually had a look into implementing that in ipfs, it's not that easy. I would go for option 2.

Also, we don't really care about the subtree topology information, as soon as we have all the blocks and their size.

**Comment by Konubinix** [comment]
I am ok with option 2. Also, may be we don't really need the size of each block.
With ls, you get the size of each subtree under the block tree. With example of the 200 Mio file, you can get the size with

``` sh
$ ipfs ls QmXo4G557RDJQfVjg9fKW5RJkUyPJ3YS6WGEw934ZcQeVT|cut -f2 -d' '|awk '{s+=$1 / 1024. / 1024.} END {print s}'
200.047
```

This needs only one call to ipfs, against 805 in the worst case scenario (all blocks being differents).

**Comment by MichaelMure** [comment]
I'm not sure it would be enough as we need the size of each block to compute an accurate progress. Also note that IPFS now use a different algorithm for splitting a file in block and they don't have a constant size anymore.

That said, we wouldn't need this information if we had an IPFS api to retrieve speed, progress, current download... https://github.com/ipfs/go-ipfs/issues/930

**Comment by Konubinix** [comment]
Hmm you are right. I have the feeling that the recursive ls calls to get the blocks sizes will spend much time implementing and will be obsoleted by the addition of the feature in ipfs.

I propose to wait to see if ipfs fix the problem on their side.
